site_name: Django Habitat
site_url: https://github.com/regisec/django-habitat/
site_description: Django Habitat - It can be simple

repo_url: https://github.com/regisec/django-habitat/

markdown_extensions:
 - toc:
    anchorlink: True